version: "3.4"

name: yudao-system

services:
    mysql:
        container_name: my_dev_yudao_mysql
        image: registry.cn-beijing.aliyuncs.com/simuhunluo/mysql:8
        restart: unless-stopped
        tty: true
        ports:
            - "17306:3306"
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE:-ruoyi-vue-pro}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-2tlci1lbnRyeXBvaW50LWluaXRkYi5kL}
        volumes:
            - mysql:/var/lib/mysql/
            - ./sql/mysql/ruoyi-vue-pro.sql:/docker-entrypoint-initdb.d/ruoyi-vue-pro.sql:ro

    redis:
        container_name: my_dev_yudao_redis
        image: registry.cn-beijing.aliyuncs.com/simuhunluo/redis:6-alpine
        restart: unless-stopped
        ports:
            - "17379:6379"
        volumes:
            - redis:/data

    server:
        container_name: my_dev_yudao_server
        build:
            context: ./yudao-server/
        image: registry.cn-beijing.aliyuncs.com/simuhunluo/my_dev_yudao_server:1.0
        restart: unless-stopped
        ports:
            - "17080:48080"
        environment:
            # https://github.com/polovyivan/docker-pass-configs-to-container
            SPRING_PROFILES_ACTIVE: local
            JAVA_OPTS:
                ${JAVA_OPTS:-
                -Xms512m
                -Xmx512m
                -Djava.security.egd=file:/dev/./urandom
                }
            ARGS:
                --spring.datasource.dynamic.datasource.master.url=${MASTER_DATASOURCE_URL:-jdbc:mysql://my_dev_yudao_mysql:3306/ruoyi-vue-pro?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true}
                --spring.datasource.dynamic.datasource.master.username=${MASTER_DATASOURCE_USERNAME:-root}
                --spring.datasource.dynamic.datasource.master.password=${MASTER_DATASOURCE_PASSWORD:-2tlci1lbnRyeXBvaW50LWluaXRkYi5kL}
                --spring.datasource.dynamic.datasource.slave.url=${SLAVE_DATASOURCE_URL:-jdbc:mysql://my_dev_yudao_mysql:3306/ruoyi-vue-pro?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true}
                --spring.datasource.dynamic.datasource.slave.username=${SLAVE_DATASOURCE_USERNAME:-root}
                --spring.datasource.dynamic.datasource.slave.password=${SLAVE_DATASOURCE_PASSWORD:-2tlci1lbnRyeXBvaW50LWluaXRkYi5kL}
                --spring.redis.host=${REDIS_HOST:-my_dev_yudao_redis}
        depends_on:
            - mysql
            - redis

volumes:
    mysql:
        driver: local
    redis:
        driver: local
